import type { GridItem } from '@/stores/types'

export interface GridTemplate {
	id: string
	name: string
	description: string
	grids: GridItem[]
}

export const gridTemplates: GridTemplate[] = [
	{
		id: 'holy-grail',
		name: 'Holy Grail Layout',
		description: 'Classic header, footer, sidebar, and main content layout',
		grids: [
			{
				id: 'holy-grail-container',
				name: 'Holy Grail Layout',
				isGridContainer: true,
				gridTemplateColumns: '200px 1fr 200px',
				gridTemplateRows: '80px 1fr 60px',
				gap: '16px',
				styles: {
					backgroundColor: '#f8fafc',
					border: '2px solid #e2e8f0',
					borderRadius: '8px',
					padding: '16px',
					minHeight: '600px',
				},
				children: [
					{
						id: 'holy-grail-header',
						name: 'Header',
						isGridContainer: false,
						gridColumnStart: '1',
						gridColumnEnd: '4',
						gridRowStart: '1',
						gridRowEnd: '2',
						styles: {
							backgroundColor: '#3b82f6',
							border: '1px solid #2563eb',
							borderRadius: '6px',
							padding: '16px',
						},
						children: [],
					},
					{
						id: 'holy-grail-sidebar',
						name: 'Sidebar',
						isGridContainer: false,
						gridColumnStart: '1',
						gridColumnEnd: '2',
						gridRowStart: '2',
						gridRowEnd: '3',
						styles: {
							backgroundColor: '#e0e7ff',
							border: '1px solid #c7d2fe',
							borderRadius: '6px',
							padding: '16px',
						},
						children: [],
					},
					{
						id: 'holy-grail-main',
						name: 'Main Content',
						isGridContainer: false,
						gridColumnStart: '2',
						gridColumnEnd: '3',
						gridRowStart: '2',
						gridRowEnd: '3',
						styles: {
							backgroundColor: '#ffffff',
							border: '1px solid #e2e8f0',
							borderRadius: '6px',
							padding: '24px',
						},
						children: [],
					},
					{
						id: 'holy-grail-aside',
						name: 'Aside',
						isGridContainer: false,
						gridColumnStart: '3',
						gridColumnEnd: '4',
						gridRowStart: '2',
						gridRowEnd: '3',
						styles: {
							backgroundColor: '#fef3c7',
							border: '1px solid #fde68a',
							borderRadius: '6px',
							padding: '16px',
						},
						children: [],
					},
					{
						id: 'holy-grail-footer',
						name: 'Footer',
						isGridContainer: false,
						gridColumnStart: '1',
						gridColumnEnd: '4',
						gridRowStart: '3',
						gridRowEnd: '4',
						styles: {
							backgroundColor: '#1e293b',
							border: '1px solid #0f172a',
							borderRadius: '6px',
							padding: '16px',
						},
						children: [],
					},
				],
			},
		],
	},
	{
		id: 'dashboard',
		name: 'Dashboard Grid',
		description: 'Modern dashboard with stats cards and main content',
		grids: [
			{
				id: 'dashboard-container',
				name: 'Dashboard',
				isGridContainer: true,
				gridTemplateColumns: 'repeat(4, 1fr)',
				gridTemplateRows: 'auto 1fr',
				gap: '20px',
				styles: {
					backgroundColor: '#f8fafc',
					border: '2px solid #e2e8f0',
					borderRadius: '8px',
					padding: '24px',
					minHeight: '600px',
				},
				children: [
					{
						id: 'stat-card-1',
						name: 'Stat Card 1',
						isGridContainer: false,
						gridColumnStart: '1',
						gridColumnEnd: '2',
						gridRowStart: '1',
						gridRowEnd: '2',
						styles: {
							backgroundColor: '#dbeafe',
							border: '1px solid #93c5fd',
							borderRadius: '8px',
							padding: '20px',
							minHeight: '120px',
						},
						children: [],
					},
					{
						id: 'stat-card-2',
						name: 'Stat Card 2',
						isGridContainer: false,
						gridColumnStart: '2',
						gridColumnEnd: '3',
						gridRowStart: '1',
						gridRowEnd: '2',
						styles: {
							backgroundColor: '#dcfce7',
							border: '1px solid #86efac',
							borderRadius: '8px',
							padding: '20px',
							minHeight: '120px',
						},
						children: [],
					},
					{
						id: 'stat-card-3',
						name: 'Stat Card 3',
						isGridContainer: false,
						gridColumnStart: '3',
						gridColumnEnd: '4',
						gridRowStart: '1',
						gridRowEnd: '2',
						styles: {
							backgroundColor: '#fef3c7',
							border: '1px solid #fde68a',
							borderRadius: '8px',
							padding: '20px',
							minHeight: '120px',
						},
						children: [],
					},
					{
						id: 'stat-card-4',
						name: 'Stat Card 4',
						isGridContainer: false,
						gridColumnStart: '4',
						gridColumnEnd: '5',
						gridRowStart: '1',
						gridRowEnd: '2',
						styles: {
							backgroundColor: '#fce7f3',
							border: '1px solid #f9a8d4',
							borderRadius: '8px',
							padding: '20px',
							minHeight: '120px',
						},
						children: [],
					},
					{
						id: 'main-chart',
						name: 'Main Chart',
						isGridContainer: false,
						gridColumnStart: '1',
						gridColumnEnd: '4',
						gridRowStart: '2',
						gridRowEnd: '3',
						styles: {
							backgroundColor: '#ffffff',
							border: '1px solid #e2e8f0',
							borderRadius: '8px',
							padding: '24px',
							minHeight: '350px',
						},
						children: [],
					},
					{
						id: 'sidebar-widget',
						name: 'Sidebar Widget',
						isGridContainer: false,
						gridColumnStart: '4',
						gridColumnEnd: '5',
						gridRowStart: '2',
						gridRowEnd: '3',
						styles: {
							backgroundColor: '#f1f5f9',
							border: '1px solid #cbd5e1',
							borderRadius: '8px',
							padding: '20px',
							minHeight: '350px',
						},
						children: [],
					},
				],
			},
		],
	},
	{
		id: 'gallery',
		name: 'Image Gallery',
		description: 'Responsive masonry-style image gallery',
		grids: [
			{
				id: 'gallery-container',
				name: 'Gallery',
				isGridContainer: true,
				gridTemplateColumns: 'repeat(4, 1fr)',
				gridAutoRows: '150px',
				gridAutoFlow: 'dense',
				gap: '16px',
				styles: {
					backgroundColor: '#f8fafc',
					border: '2px solid #e2e8f0',
					borderRadius: '8px',
					padding: '16px',
					minHeight: '600px',
				},
				children: [
					{
						id: 'gallery-1',
						name: 'Image 1',
						isGridContainer: false,
						gridColumnStart: '1',
						gridColumnEnd: '2',
						gridRowStart: '1',
						gridRowEnd: '2',
						styles: {
							backgroundColor: '#dbeafe',
							border: '1px solid #93c5fd',
							borderRadius: '8px',
						},
						children: [],
					},
					{
						id: 'gallery-2',
						name: 'Image 2 (Tall)',
						isGridContainer: false,
						gridColumnStart: '2',
						gridColumnEnd: '3',
						gridRowStart: '1',
						gridRowEnd: '3',
						styles: {
							backgroundColor: '#dcfce7',
							border: '1px solid #86efac',
							borderRadius: '8px',
						},
						children: [],
					},
					{
						id: 'gallery-3',
						name: 'Image 3',
						isGridContainer: false,
						gridColumnStart: '3',
						gridColumnEnd: '4',
						gridRowStart: '1',
						gridRowEnd: '2',
						styles: {
							backgroundColor: '#fef3c7',
							border: '1px solid #fde68a',
							borderRadius: '8px',
						},
						children: [],
					},
					{
						id: 'gallery-4',
						name: 'Image 4 (Wide)',
						isGridContainer: false,
						gridColumnStart: '4',
						gridColumnEnd: '5',
						gridRowStart: '1',
						gridRowEnd: '2',
						styles: {
							backgroundColor: '#fce7f3',
							border: '1px solid #f9a8d4',
							borderRadius: '8px',
						},
						children: [],
					},
					{
						id: 'gallery-5',
						name: 'Image 5',
						isGridContainer: false,
						gridColumnStart: '1',
						gridColumnEnd: '2',
						gridRowStart: '2',
						gridRowEnd: '3',
						styles: {
							backgroundColor: '#e0e7ff',
							border: '1px solid #c7d2fe',
							borderRadius: '8px',
						},
						children: [],
					},
					{
						id: 'gallery-6',
						name: 'Image 6 (Wide)',
						isGridContainer: false,
						gridColumnStart: '3',
						gridColumnEnd: '5',
						gridRowStart: '2',
						gridRowEnd: '3',
						styles: {
							backgroundColor: '#fbcfe8',
							border: '1px solid #f9a8d4',
							borderRadius: '8px',
						},
						children: [],
					},
					{
						id: 'gallery-7',
						name: 'Image 7',
						isGridContainer: false,
						gridColumnStart: '1',
						gridColumnEnd: '3',
						gridRowStart: '3',
						gridRowEnd: '4',
						styles: {
							backgroundColor: '#ddd6fe',
							border: '1px solid #c4b5fd',
							borderRadius: '8px',
						},
						children: [],
					},
					{
						id: 'gallery-8',
						name: 'Image 8 (Tall)',
						isGridContainer: false,
						gridColumnStart: '3',
						gridColumnEnd: '4',
						gridRowStart: '3',
						gridRowEnd: '5',
						styles: {
							backgroundColor: '#fed7aa',
							border: '1px solid #fdba74',
							borderRadius: '8px',
						},
						children: [],
					},
					{
						id: 'gallery-9',
						name: 'Image 9',
						isGridContainer: false,
						gridColumnStart: '4',
						gridColumnEnd: '5',
						gridRowStart: '3',
						gridRowEnd: '4',
						styles: {
							backgroundColor: '#bfdbfe',
							border: '1px solid #93c5fd',
							borderRadius: '8px',
						},
						children: [],
					},
				],
			},
		],
	},
	{
		id: 'card-layout',
		name: 'Card Layout',
		description: 'Responsive card grid for products or content',
		grids: [
			{
				id: 'card-container',
				name: 'Cards',
				isGridContainer: true,
				gridTemplateColumns: 'repeat(3, 1fr)',
				gridTemplateRows: 'repeat(2, 1fr)',
				gap: '24px',
				styles: {
					backgroundColor: '#f8fafc',
					border: '2px solid #e2e8f0',
					borderRadius: '8px',
					padding: '24px',
					minHeight: '500px',
				},
				children: [
					{
						id: 'card-1',
						name: 'Card 1',
						isGridContainer: false,
						styles: {
							backgroundColor: '#ffffff',
							border: '1px solid #e2e8f0',
							borderRadius: '12px',
							padding: '20px',
							minHeight: '200px',
						},
						children: [],
					},
					{
						id: 'card-2',
						name: 'Card 2',
						isGridContainer: false,
						styles: {
							backgroundColor: '#ffffff',
							border: '1px solid #e2e8f0',
							borderRadius: '12px',
							padding: '20px',
							minHeight: '200px',
						},
						children: [],
					},
					{
						id: 'card-3',
						name: 'Card 3',
						isGridContainer: false,
						styles: {
							backgroundColor: '#ffffff',
							border: '1px solid #e2e8f0',
							borderRadius: '12px',
							padding: '20px',
							minHeight: '200px',
						},
						children: [],
					},
					{
						id: 'card-4',
						name: 'Card 4',
						isGridContainer: false,
						styles: {
							backgroundColor: '#ffffff',
							border: '1px solid #e2e8f0',
							borderRadius: '12px',
							padding: '20px',
							minHeight: '200px',
						},
						children: [],
					},
					{
						id: 'card-5',
						name: 'Card 5',
						isGridContainer: false,
						styles: {
							backgroundColor: '#ffffff',
							border: '1px solid #e2e8f0',
							borderRadius: '12px',
							padding: '20px',
							minHeight: '200px',
						},
						children: [],
					},
					{
						id: 'card-6',
						name: 'Card 6',
						isGridContainer: false,
						styles: {
							backgroundColor: '#ffffff',
							border: '1px solid #e2e8f0',
							borderRadius: '12px',
							padding: '20px',
							minHeight: '200px',
						},
						children: [],
					},
				],
			},
		],
	},
	{
		id: 'magazine',
		name: 'Magazine Layout',
		description: 'Editorial-style asymmetric grid layout',
		grids: [
			{
				id: 'magazine-container',
				name: 'Magazine',
				isGridContainer: true,
				gridTemplateColumns: 'repeat(6, 1fr)',
				gridTemplateRows: 'repeat(4, 150px)',
				gridAutoFlow: 'dense',
				gap: '16px',
				styles: {
					backgroundColor: '#f8fafc',
					border: '2px solid #e2e8f0',
					borderRadius: '8px',
					padding: '16px',
					minHeight: '650px',
				},
				children: [
					{
						id: 'mag-hero',
						name: 'Hero Article',
						isGridContainer: false,
						gridColumnStart: '1',
						gridColumnEnd: '5',
						gridRowStart: '1',
						gridRowEnd: '3',
						styles: {
							backgroundColor: '#1e293b',
							border: '1px solid #0f172a',
							borderRadius: '8px',
							padding: '24px',
						},
						children: [],
					},
					{
						id: 'mag-side-1',
						name: 'Side Article 1',
						isGridContainer: false,
						gridColumnStart: '5',
						gridColumnEnd: '7',
						gridRowStart: '1',
						gridRowEnd: '2',
						styles: {
							backgroundColor: '#dbeafe',
							border: '1px solid #93c5fd',
							borderRadius: '8px',
							padding: '16px',
						},
						children: [],
					},
					{
						id: 'mag-side-2',
						name: 'Side Article 2',
						isGridContainer: false,
						gridColumnStart: '5',
						gridColumnEnd: '7',
						gridRowStart: '2',
						gridRowEnd: '3',
						styles: {
							backgroundColor: '#fef3c7',
							border: '1px solid #fde68a',
							borderRadius: '8px',
							padding: '16px',
						},
						children: [],
					},
					{
						id: 'mag-small-1',
						name: 'Small Article 1',
						isGridContainer: false,
						gridColumnStart: '1',
						gridColumnEnd: '3',
						gridRowStart: '3',
						gridRowEnd: '5',
						styles: {
							backgroundColor: '#dcfce7',
							border: '1px solid #86efac',
							borderRadius: '8px',
							padding: '16px',
						},
						children: [],
					},
					{
						id: 'mag-small-2',
						name: 'Small Article 2',
						isGridContainer: false,
						gridColumnStart: '3',
						gridColumnEnd: '5',
						gridRowStart: '3',
						gridRowEnd: '5',
						styles: {
							backgroundColor: '#fce7f3',
							border: '1px solid #f9a8d4',
							borderRadius: '8px',
							padding: '16px',
						},
						children: [],
					},
					{
						id: 'mag-small-3',
						name: 'Small Article 3',
						isGridContainer: false,
						gridColumnStart: '5',
						gridColumnEnd: '7',
						gridRowStart: '3',
						gridRowEnd: '5',
						styles: {
							backgroundColor: '#e0e7ff',
							border: '1px solid #c7d2fe',
							borderRadius: '8px',
							padding: '16px',
						},
						children: [],
					},
				],
			},
		],
	},
]
